-- RPC para buscar eventos com posts em uma única query (elimina N+1)
CREATE OR REPLACE FUNCTION public.get_events_with_posts(p_agency_id uuid DEFAULT NULL, p_is_active boolean DEFAULT NULL)
RETURNS TABLE (
  event_id uuid,
  event_title text,
  event_description text,
  event_date timestamp with time zone,
  event_location text,
  event_is_active boolean,
  event_agency_id uuid,
  event_created_by uuid,
  event_created_at timestamp with time zone,
  event_updated_at timestamp with time zone,
  event_setor text,
  event_numero_de_vagas integer,
  event_required_posts integer,
  event_required_sales integer,
  event_total_required_posts integer,
  event_is_approximate_total boolean,
  event_accept_posts boolean,
  event_accept_sales boolean,
  event_event_slug text,
  event_event_image_url text,
  event_event_purpose text,
  event_target_gender text[],
  event_producer_name text,
  event_ticketer_email text,
  event_internal_notes text,
  event_whatsapp_group_url text,
  event_whatsapp_group_title text,
  event_require_instagram_link boolean,
  event_require_post_screenshot boolean,
  event_require_profile_screenshot boolean,
  event_auto_activate_at timestamp with time zone,
  event_auto_deactivate_at timestamp with time zone,
  post_id uuid,
  post_event_id uuid,
  post_post_number integer,
  post_deadline timestamp with time zone,
  post_created_by uuid,
  post_created_at timestamp with time zone,
  post_updated_at timestamp with time zone,
  post_agency_id uuid,
  post_post_type text
)
LANGUAGE sql
STABLE SECURITY DEFINER
SET search_path TO 'public'
AS $$
  SELECT 
    e.id as event_id,
    e.title as event_title,
    e.description as event_description,
    e.event_date,
    e.location as event_location,
    e.is_active as event_is_active,
    e.agency_id as event_agency_id,
    e.created_by as event_created_by,
    e.created_at as event_created_at,
    e.updated_at as event_updated_at,
    e.setor as event_setor,
    e.numero_de_vagas as event_numero_de_vagas,
    e.required_posts as event_required_posts,
    e.required_sales as event_required_sales,
    e.total_required_posts as event_total_required_posts,
    e.is_approximate_total as event_is_approximate_total,
    e.accept_posts as event_accept_posts,
    e.accept_sales as event_accept_sales,
    e.event_slug as event_event_slug,
    e.event_image_url as event_event_image_url,
    e.event_purpose as event_event_purpose,
    e.target_gender as event_target_gender,
    e.producer_name as event_producer_name,
    e.ticketer_email as event_ticketer_email,
    e.internal_notes as event_internal_notes,
    e.whatsapp_group_url as event_whatsapp_group_url,
    e.whatsapp_group_title as event_whatsapp_group_title,
    e.require_instagram_link as event_require_instagram_link,
    e.require_post_screenshot as event_require_post_screenshot,
    e.require_profile_screenshot as event_require_profile_screenshot,
    e.auto_activate_at as event_auto_activate_at,
    e.auto_deactivate_at as event_auto_deactivate_at,
    p.id as post_id,
    p.event_id as post_event_id,
    p.post_number as post_post_number,
    p.deadline as post_deadline,
    p.created_by as post_created_by,
    p.created_at as post_created_at,
    p.updated_at as post_updated_at,
    p.agency_id as post_agency_id,
    p.post_type as post_post_type
  FROM events e
  LEFT JOIN posts p ON p.event_id = e.id
  WHERE (p_agency_id IS NULL OR e.agency_id = p_agency_id)
    AND (p_is_active IS NULL OR e.is_active = p_is_active)
  ORDER BY e.event_date ASC NULLS LAST, p.post_number ASC;
$$;